apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwMi5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYTNWaVpXRmtiV2x1T2xaaGJHRjRlVUF4TWpNPSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: "2023-02-15T06:59:39Z"
  name: regcred
  namespace: valaxy
  resourceVersion: "3180"
  uid: 87cfe99f-293f-41ce-af07-0b4b107a31b2
type: kubernetes.io/dockerconfigjson
